### ISSUE TITLE
Under "Services" "Monitoring" Topic

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#1]
Put this:
	- Data that doesn't enhance safety, profitability, or machine health is useless or even problematic. Motornostix® monitors and collects the data, and more importantly, mines the data to enhance day-to-day and long-term operations by giving plant personnel and management information to be more effective.
	- Motornostix® systems provide 24/7/365 monitoring.
	- All your shredder health and performance data is streamed to our Tier-3 Data Center where it is available to you 24x7.
	- We keep ALL your history online. Want to compare last month to this month? It’s online. So is last year and the year before going all the way back. This is a really powerful feature of our system typically not provided by process control systems at recycling plants.
	- This is one of the main reasons that our large corporate customers really like our system, since ALL the data for ALL the plants is available ALL the time at your fingertips.
	- Our system also collects data on EVERY motor run-up including inrush current, motor speed and time-to-rated speed. This is incredibly helpful information to have on hand when troubleshooting a motor or liquid rheostat-related problem. We often help our customers fine-tune their LR brine concentration using this data. No one else does this.

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_mUUsRwaHyX](https://user-images.githubusercontent.com/32921440/169464674-715c401f-7754-44d6-b1a5-4d6f4113a423.png)
