### ISSUE TITLE
Change contents under "Our Plan"

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#10]
Put this:
We monitor your equipment 24/7/365. We set good alarm levels in conjunction with your plant staff. We automatically assess incoming data against preset alarm levels. We notify plant personnel of urgent issues. We report findings, both performance and health, in a timely manner.

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_RLJ2Ju9wQ1](https://user-images.githubusercontent.com/32921440/169486864-2288d8cb-4193-490b-b18f-0385ddcb1f78.png)
