### ISSUE TITLE
Replace text under "Services" main heading

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#11]
Put this:
Knowing when to run equipment and when to repair equipment can mean the difference between safe operation and long equipment life versus less desirable alternatives like unplanned downtime and catastrophic failures. Skilled operators often feel or sense equipment issues but have no way to know if their sensations are correct or to communicate their sensations to management. Motornostix® sensors are connected directly to the shredder and to the drive motor[s], looking at three axes of bearing data, and can sense issues reliably to aid in problem detection and identification. We also contribute to efficient plant operation by monitoring values such as power consumption and output, offering reports on these items to improve daily throughput.

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_6hDnwX7PTw](https://user-images.githubusercontent.com/32921440/169464506-c5dabae8-8a43-4f49-bb0b-20ee16cc4ae1.png)
