### ISSUE TITLE
Replace "We are professional" and the text under it

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#12]
With:
"Expertise"
and
"A scrap metal recycling business requires significant expertise and experience to remain profitable."

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_2Twq8bk6gQ](https://user-images.githubusercontent.com/32921440/169473682-2a8dc3ce-1d8d-45d3-acf7-de82d04d2dff.png)


---

![chrome_6JZFiXtt6t](https://user-images.githubusercontent.com/32921440/169473882-dcee12e9-cadf-434c-9d70-5ee4bbdc544b.jpg)
