### ISSUE TITLE
Change "At vero eos et accusamus" and the text under it

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#13]
With:
"Safety"
and 
"Scrap metal recycling is dangerous and can be hazardous to personnel and the environment."

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_7Q6ZtzEt0m](https://user-images.githubusercontent.com/32921440/169474083-35481de4-c1c3-4442-b68c-48b21eee7aad.png)
