### ISSUE TITLE
Replace "Temporibus autem quibusdam" and text under it 

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#14]
With
"Operations"
and 
"Metal recycling shredders take significant abuse even during normal operations."

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_hWtlQtxpno](https://user-images.githubusercontent.com/32921440/169474211-ac930769-7f9c-4b78-9745-2fcf764365c8.png)
