### ISSUE TITLE
Replace "Nam libero tempore" and text under it 

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#15]
With:
"Ability"
and 
"The ability to keep this equipment operating safely when it is needed is central to the healthy operation of a metal shredding facility."

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_2ZalVNLQM7](https://user-images.githubusercontent.com/32921440/169474372-9fc01b33-1b22-46ca-9dd4-227d28cf4a60.png)
