### ISSUE TITLE
Replace picture under "About Us" "Our Mission" 

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#16]
@anton-po-github Use this picture as a placeholder
![IMG_0685](https://user-images.githubusercontent.com/47575074/169396821-1216df90-4f00-48de-8226-5eeeb14fecc6.jpg)

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

---

There were some issues with this photo.

I will try to explain.


![chrome_FSw21CIp9O](https://user-images.githubusercontent.com/32921440/169486200-43ab9956-521b-44cd-a3b9-72e22fc16611.jpg)


---

so far it’s hard for me to find a good solution, a difference of 1000 pixels is a lot, that is, if I stretch the photo, it will be very noticeable on the quality of the photo itself.

I can crop all 3 photos and make all 3 photos the same, but their size will be clearly smaller.

let's say the size of all 3 photos will be

`Width = 2500`

`Height = 2500`

**Comment by mikedrich** [comment]
No worries @anton-po-github 
These are not the real pictures anyway so just leave it as-is.
