### ISSUE TITLE
Replace picture under "About Us" "Our Plan"

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#17]
with:
![IMG_0755](https://user-images.githubusercontent.com/47575074/169397128-82c4ea64-31d5-4341-a3cc-ee42f46d31e1.jpg)

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_Zo7S0rzCuL](https://user-images.githubusercontent.com/32921440/169484776-efb4ac3b-38a5-4158-a79e-b92fbdfd4952.png)
