### ISSUE TITLE
Replace picture under "About Us" "Our Vision"

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#18]
with
![IMG_0759](https://user-images.githubusercontent.com/47575074/169397515-ec816c98-d1a7-4f6f-82c8-3f7c33832af9.jpg)

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_e2XGoqwzg6](https://user-images.githubusercontent.com/32921440/169484640-32c3b14d-6e51-4167-a07b-29191b6ba2df.png)


---

we also need to replace the text for `Our Vision`

**Comment by mikedrich** [comment]
@anton-po-github 
Please change the aforementioned text to"
"Our vision is to provide an innovative, online, web-based condition monitoring system for electrical and mechanical rotating machinery in an affordable manner."

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_FpwpMpx0Vl](https://user-images.githubusercontent.com/32921440/169541113-b4097c86-5a47-4cff-8cc7-6c4a8c13895e.png)
