### ISSUE TITLE
Under "Services" "Alarms" Topic

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#2]
Put this:
	- From the monitored data, Motornostix® provides alerts, alarms and information to protect the health and safety of personnel, equipment and the environment around metal shredders.
	- All key measurables both from our sensors and the Multilin are collected, measured and monitored in real-time. Alarms are raised to notify you of developing health conditions during your production run. These can be anything from surfacing flaky RTDs (e.g. damaged, over-temperature or loose terminal connections) to vibration alarms indicating damaging vibration impacting machine health.

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_3fngS9wr53](https://user-images.githubusercontent.com/32921440/169464819-ccd1ce6a-03c0-46e2-9043-a839229df0d6.png)
