### ISSUE TITLE
Change contents

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#20]
Change contents:
"The ability to keep this equipment operating safely when it is needed is central to the healthy operation of a metal shredding facility."
to
"The ability to keep shredding equipment operating safely when it is needed is central to the healthy operation of a metal shredding facility. Motornostix® knows how to help."

Change:
"Metal recycling shredders take significant abuse even during normal operations."
to 
"Metal recycling shredders take significant abuse even during normal operations and Motornostix® knows how to minimize the damage."

Change:
"Scrap metal recycling is dangerous and can be hazardous to personnel and the environment."
to
"Scrap metal recycling is dangerous and can be hazardous to personnel and the environment. Motornostix® knows how to help."

Change:
"A scrap metal recycling business requires significant expertise and experience to remain profitable."
to
"A scrap metal recycling business requires significant expertise and experience to remain profitable. Motornostix® has this expertise and experience."

Change:
"Nam libero tempore" to "Capacity"
and 
"Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum."
to
"Motornostix® can help maximize the capacity of your equipment with performance and health information."

**Comment by anton-po-github** [comment]
@mikedrich 

done.


https://user-images.githubusercontent.com/32921440/169532032-f100ad1e-7789-487a-acde-5045745fa8a6.mp4
