### ISSUE TITLE
Add some of our current customers under "Our Clients"

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#21]
![image](https://user-images.githubusercontent.com/47575074/169543059-9b801493-4609-470b-aa4d-9b1b79930710.png)

![image](https://user-images.githubusercontent.com/47575074/169543190-cf114a7a-1c0a-47d2-8d26-81c6c7c11ea7.png)

![image](https://user-images.githubusercontent.com/47575074/169543355-fe43fb83-d31b-4434-bd13-ae581b2eb1be.png)

![image](https://user-images.githubusercontent.com/47575074/169543593-72f96fd2-7afc-437b-9207-33180704dc5d.png)

![image](https://user-images.githubusercontent.com/47575074/169543830-03c04d09-cee1-495f-8830-095b9b68c9a7.png)

![image](https://user-images.githubusercontent.com/47575074/169544097-8496d1e6-42f0-482f-a9bb-3d86d429c4cb.png)

![image](https://user-images.githubusercontent.com/47575074/169544312-a20ba4c4-c73e-4af1-b554-bec42004f322.png)

![image](https://user-images.githubusercontent.com/47575074/169544497-0047bfd2-7d13-4c39-b8d4-ca9e26fdab61.png)

![image](https://user-images.githubusercontent.com/47575074/169544649-a5f488ee-7d1a-45d1-ad59-be70f4c26911.png)

![image](https://user-images.githubusercontent.com/47575074/169544823-7ee54a45-3071-4cc8-9424-37afeb4f84d8.png)

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_mNmzwc8PSt](https://user-images.githubusercontent.com/32921440/169575434-843a197e-35bb-4013-bd4a-46a4e00b950a.png)
