### ISSUE TITLE
Under "Facts" put the following

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#22]
Replace "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque" with "Our commitment to our customers success is evidenced by our longevity in this industry."

Replace "Clients" and the number with:
1,410,360+
Continuous 
Monitoring 
Hours

Replace "Projects" and the number with:
7,000,000,000+
Data
Points
Collected

Replace number (1364) associated with "Hours Of Support" to 
750,000+

Replace "Hard Workers" and number with:
250,000+ 
Hours of
Experience

**Comment by anton-po-github** [comment]
@mikedrich

improved.

![chrome_tUWoemd77T](https://user-images.githubusercontent.com/32921440/169574769-eba9ae65-41db-48b1-838c-5368590bff10.png)
