### ISSUE TITLE
Minor tweeks

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#23]
Please remove the comma after 498136:
![image](https://user-images.githubusercontent.com/47575074/169559871-40f236dc-35f8-4672-98b0-f6e38b716dbe.png)

Please remove the quote after .com:
![image](https://user-images.githubusercontent.com/47575074/169559985-0d6f853c-9f45-412f-be79-6862d0bc60ea.png)

Please change this text from:
"Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus. Scelerisque felis imperdiet proin fermentum leo. Amet volutpat consequat mauris nunc congue."
to
"We watch your equipment so you can focus on running your business."

**Comment by anton-po-github** [comment]
@mikedrich 

done

![chrome_adWIGw5W3g](https://user-images.githubusercontent.com/32921440/169578304-33bfb1d2-ecd5-4332-b1c0-d5ed82d4e35c.png)


---

![chrome_dCodWAxdxn](https://user-images.githubusercontent.com/32921440/169578355-34c5e557-14a1-41db-90cf-6ecdd12f0d32.png)


---

![chrome_1Hm6nM5UoK](https://user-images.githubusercontent.com/32921440/169578531-bd1236d7-cced-4efe-a479-7d21a071c6d3.png)
