### ISSUE TITLE
Replace picture over "Our Mission" with this one:

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#24]
![Image from iOS](https://user-images.githubusercontent.com/47575074/169561538-b0a418a8-3ee8-4ab1-b274-ceacb065cdfb.jpg)

**Comment by anton-po-github** [comment]
@mikedrich 

done

![chrome_ItOuxKzvGI](https://user-images.githubusercontent.com/32921440/169578179-f2431adc-23a6-488e-9839-04040ff8f997.png)
