### ISSUE TITLE
Replace picture behind Facts

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#25]
With this:
![IMG_1580](https://user-images.githubusercontent.com/47575074/169577984-e74e3dae-5783-422e-afd2-744c2eed6ed4.jpg)

**Comment by mikedrich** [comment]
@anton-po-github 
Also please remove the the BizPage images from the Facts section

**Comment by anton-po-github** [comment]
@mikedrich 

done


https://user-images.githubusercontent.com/32921440/169580391-ec174985-9340-47cf-a008-e2f5077a73a8.mp4
