### ISSUE TITLE
Replace customer ICON for UPSTATE

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#27]
Remove this:
![image](https://user-images.githubusercontent.com/47575074/169578898-9f7815c3-cd9f-4582-8d0d-45d5dd91b0bd.png)

Insert this:
![image](https://user-images.githubusercontent.com/47575074/169578787-3a8b18ac-274b-44bd-9aa8-933e25e57449.png)

**Comment by anton-po-github** [comment]
@mikedrich 

done

![chrome_jMG743BrjL](https://user-images.githubusercontent.com/32921440/169580812-b03136c7-dcc2-4803-9403-842d750e380c.png)
