### ISSUE TITLE
Replace text under "Our Newsletter"

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#28]
Replace this:
"Tamen quem nulla quae legam multos aute sint culpa legam noster magna veniam enim veniam illum dolore legam minim quorum culpa amet magna export quem marada parida nodela caramase seza."

with:

"We don't have a newsletter but if we did we would want you to sign up for it here and you would LOVE it when you received it... Get UPDATES from us (no SPAM)."

**Comment by anton-po-github** [comment]
@mikedrich 

done

![chrome_Xz8afRiqbC](https://user-images.githubusercontent.com/32921440/169580731-89ccf79c-0eaa-4cfb-85d2-5e603d079490.png)
