### ISSUE TITLE
Minor tweak in Installation section

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#29]
Change:
"Our system come pre-assembled (think Lego) "

to 
"Our system comes pre-assembled (think Legos) "

**Comment by anton-po-github** [comment]
@mikedrich 

done

![chrome_wjKs4xH7XW](https://user-images.githubusercontent.com/32921440/169580976-f594f681-b72a-400e-91e0-25c59b86542c.png)
