### ISSUE TITLE
Under "Services" "Analysis" Topic

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#3]
Put this:
	- Automatically mining data on the backend
	- Tools for analysis if needed
	- Analysis if needed
	- Expertise if needed
	- The Motornostix® system captures vibration waveforms (think bearing MRI or X-Ray) on each bearing in all 3 axes (axial, horizontal & vertical) and deconstructs these comprehensive measurements into their components parts (e.g. comparing synchronous vs non-synchronous energy as a basic example) to evaluate bearing health over time. Waveforms are captured at idle on every run day, thus forming a comprehensive picture of machine health over time. And all of this information is available via our portal to you, and your vendors as permitted.

**Comment by anton-po-github** [comment]
@mikedrich 

improved.


![chrome_EzxB8og6wX](https://user-images.githubusercontent.com/32921440/169464906-ae1aff67-371e-4f74-a39b-21217f5cb524.png)
