### ISSUE TITLE
Replace text under "Lorem Ipsum Delino" "Dolor Sitema" and "Sed ut perspiciatis"

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#30]
Replace:
"[Lorem Ipsum Delino](https://anton-po-github.github.io/motornostixusa/index.html)"

with:
"We Monitor"

Replace:
"Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident"

With:
"Motornostix™ provides a complete, cost-effective condition monitoring system designed to pre-empt failures, minimize downtime and increase productivity. Our systems are non-intrusive and provide a continuous monitoring function."

-----

Replace:
"[Dolor Sitema](https://anton-po-github.github.io/motornostixusa/index.html)"

with:
"We Analyze"

Replace:
"Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata"

with:
"Motornostix™ USA provides a complete condition monitoring service that includes all aspects of design, installation, commissioning and support. The service is provided on the basis of a monthly fee that covers monitoring, upgrades, support and maintenance. We are committed to the highest standards of technical competence, safety and customer service."

----

Replace:
"[Sed ut perspiciatis](https://anton-po-github.github.io/motornostixusa/index.html)"

with:
"We Notify"

Replace:
"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur"

with:
"If conditions for an existing or impending malfunction are identified, systems provide for immediate diagnostic alarms to be directed to designated personnel such as responsible plant staff members, consultants, OEM's or repairers."

**Comment by anton-po-github** [comment]
@mikedrich 

done

![chrome_RVDaMFKQhp](https://user-images.githubusercontent.com/32921440/169638919-7eeaff3c-bdd5-4b18-aae1-3218e9906742.png)
