### ISSUE TITLE
Tweak text under "Services"

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#31]
Replace:
"the difference between safe operation and long equipment life versus less desirable alternatives like unplanned downtime and catastrophic failures. "

with:

"the difference between safe operation with long equipment life versus less desirable alternatives such as unplanned downtime and catastrophic failures. "

**Comment by anton-po-github** [comment]
@mikedrich 

done

![chrome_JzlY6YpWpg](https://user-images.githubusercontent.com/32921440/169638890-d5001479-1b63-4751-8817-f02496a52f38.png)
