### ISSUE TITLE
Move text

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#32]
Move this text from under "Services" => "Monitoring" 
• All your shredder health and performance data is streamed to our Tier-3 Data Center where it is available to you 24x7.
• We keep ALL your history online. Want to compare last month to this month? It’s online. So is last year and the year before going all the way back. This is a really powerful feature of our system typically not provided by process control systems at recycling plants.
• This is one of the main reasons that our large corporate customers really like our system, since ALL the data for ALL the plants is available ALL the time at your fingertips.

To be under "Services" => "Data Safety and Access"

**Comment by anton-po-github** [comment]
@mikedrich 

I improved it, only I did NOT quite understand this sub-point

> To be under "Services" => "Data Safety and Access"

---


![chrome_MGIMNl05tm](https://user-images.githubusercontent.com/32921440/169639019-1af38e5d-1518-46fe-b11b-2db0fbdf71b6.png)
