### ISSUE TITLE
Minor tweak under ABOUT US

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#34]
In the second sentence under ABOUT US
Change: 
"to help a metal shredders "

To

"to help metal shredders "

**Comment by anton-po-github** [comment]
@mikedrich 

done

![chrome_kaPL5f4IKf](https://user-images.githubusercontent.com/32921440/170032275-fbd66765-b330-4c8d-a5a2-86de5b9974f6.png)
