### ISSUE TITLE
Minor tweak to "We Monitor"

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#36]
@anton-po-github 

![image](https://user-images.githubusercontent.com/47575074/173613629-069a80ff-cba5-4021-a93a-0a4825d208d7.png)

After Motornostix in the first sentence add "USA".

At the end of the last sentence after "function", add "24 hours a day, 7 days a week, 365 days a year."

**Comment by anton-po-github** [comment]
@mikedrich 

done

![chrome_t725YxCLYt](https://user-images.githubusercontent.com/32921440/173758227-e0a80753-1f9a-4e86-84d5-7e1a40175b48.png)

**Comment by anton-po-github** [comment]
@mikedrich 

I close this issue.
