### ISSUE TITLE
Minor tweak to "We Notify"

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#37]
@anton-po-github 

![image](https://user-images.githubusercontent.com/47575074/173617948-defb2264-b9ec-4007-a351-6465260461cf.png)

Add "Motornostix™ USA" between "identified, systems".

**Comment by anton-po-github** [comment]
@mikedrich 

done

![chrome_cy812t3N8J](https://user-images.githubusercontent.com/32921440/173758364-96cfd404-0589-4888-88ec-5cec884ee215.png)
