### ISSUE TITLE
Under "Services" "Reporting" Topic

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#4]
Put this:
	- We provide you with two daily reports for each site – the performance report covers exactly that – how well did the site perform against expectations for the last 24h window (defined by you)? This information includes runtime, idle time, motor utilization, thermal capacity, production output and electrical efficiency. 
	- The health report details machine health metrics to answer the question – what was the impact on machine health for the performance achieved? The health report also surfaces developing machine health conditions. The report shows vibration data across the drive train in an easily-consumable format so you can compare day-on-day and investigate and identify associated root causes.
	- Motornostix® provides notifications of significant events.
	- Motornostix® provides reports of critical performance.
	- Motornostix® provides tools for monitoring and analysis.
	- Motornostix® provides protection against unplanned downtime.
	- Motornostix® provides protection against catastrophic failures

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_mdaht1S3FT](https://user-images.githubusercontent.com/32921440/169464990-af376157-6e24-4a4a-a066-8f1720c61246.png)
