### ISSUE TITLE
Under "Services" "Data Safety and Access" Topic

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#5]
Put this:
	- We store your data in a Tier-3 facility so it is safe, secure and accessible.
	- It is accessible via any device that can connect to the Internet and run a browser.
	- We have resolved a number of issues over the years by providing vendors access to customer data for troubleshooting purposes. This has reduced the lead time to resolution, greatly assisted with root cause analysis and limited the cost involved since often times no vendor visits were required. This has been particularly helpful with vendors who are not state-side, like Alstom, Actom and WEG.

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_AuqATE5Nrd](https://user-images.githubusercontent.com/32921440/169465102-a53ffd74-f959-4ee7-b7b7-e1bd0096ba5c.png)
