### ISSUE TITLE
Under "Services" "System Reliability" Topic

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#6]
Put this:
	- Industry standards for operation and security
	- The only potential damage to our system generally occurs out at the mill.
	- Our mill sensor and cables are armored and jacketed with an aerospace thermal fire-sleeve along with a stainless steel woven braid. This design has proved pretty impervious even to the destructive nature of the shredding process, but occasionally damage, either thermal (e.g. mill fire) and mechanical (e.g. car falls from in-feed chute onto our sensor) occurs.
	- Any such damage would require sensor/cable replacement at your cost.
	- If a sensor fails without any observable damage, then we offer forward replacement of the part at our cost.
	- Whilst it varies from site to site, mill sensor lifetime is often measured in years.
	- If some other component of our system fails (e.g. a computer) without overt damage, then we cover the cost of the replacement item.

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_N692j7QZX4](https://user-images.githubusercontent.com/32921440/169465203-66203781-b714-4716-96d0-2988017fe21b.png)
