### ISSUE TITLE
Add this photo as a placeholder with the ones you already added

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#7]
![Newco-Modular-Automobile-Shredder-1](https://user-images.githubusercontent.com/47575074/169361537-38e1197b-67ea-4cb2-81a0-b0fceb38450b.jpg)

**Comment by anton-po-github** [comment]
@mikedrich 

![chrome_NdSWWVaulc](https://user-images.githubusercontent.com/32921440/169467388-13c11ae0-44aa-4e91-a26c-e4af1f2ae7df.jpg)
