### ISSUE TITLE
Change "Call To Action" heading to "Installation"

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#8]
Put this under the "Installation" heading:
	- The installation cost includes all the Motornostix®-specific equipment to be installed at each site including cabinets, power systems, computer equipment, cables and sensors.
	- Our system come pre-assembled (think Lego) to ease installation and minimize downtime.
	- We generally need some help from your site electrical contractor to provide power to our cabinet, running conduit if required, and to assist with welding our junction boxes out at the mill.
	- An installation takes approx. 2-3 days depending on existing site infrastructure, and most installations typically take place over a weekend to minimize plant downtime.

Change the "Call To Action" button to "Request Information"

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_6FrtD0rSG2](https://user-images.githubusercontent.com/32921440/169472080-55ae3176-d98e-401e-b33b-32101bcb1e44.png)
