### ISSUE TITLE
Change contents under "Our Mission" 

### ISSUE THREAD

**Issue by mikedrich** [anton-po-github/motornostixusa#9]
Put this:
We aid our customers in making their facility as profitable, functional  and safe as possible by providing timely information in a helpful and practical way.

**Comment by anton-po-github** [comment]
@mikedrich 

improved.

![chrome_Il58ks7b9j](https://user-images.githubusercontent.com/32921440/169486716-5c4de8f3-d3ff-49c7-8433-76c6d0255a8d.png)
